name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup mosquitto
      run: apt-get -y install mosquitto
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Start mosquitto
      run: cd test_data && mosquitto -c ./mosquitto.conf -d
    - name: Run tests
      run: cargo test --verbose
