name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup mosquitto
      run: sudo apt-get -y install mosquitto
    - name: Switch to Rust nightly
      run: rustup default nightly
    - uses: actions/checkout@v3
    - name: Start mosquitto
      run: cd test_data && mosquitto -c ./mosquitto.conf -d && sleep 1
    - name: Run tests
      run: cargo test -F tls
